# Generated by Django 4.1.7 on 2023-03-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_endtime',
            field=models.DateField(),
        ),
    ]
